/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Page2RouteImport } from './routes/page2'
import { Route as PathlessLayoutRouteRouteImport } from './routes/_pathlessLayout/route'
import { Route as PathlessLayoutEventDateRouteImport } from './routes/_pathlessLayout/event.$date'

const Page2Route = Page2RouteImport.update({
  id: '/page2',
  path: '/page2',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRouteRoute = PathlessLayoutRouteRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutEventDateRoute = PathlessLayoutEventDateRouteImport.update({
  id: '/event/$date',
  path: '/event/$date',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/page2': typeof Page2Route
  '/event/$date': typeof PathlessLayoutEventDateRoute
}
export interface FileRoutesByTo {
  '/page2': typeof Page2Route
  '/event/$date': typeof PathlessLayoutEventDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pathlessLayout': typeof PathlessLayoutRouteRouteWithChildren
  '/page2': typeof Page2Route
  '/_pathlessLayout/event/$date': typeof PathlessLayoutEventDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/page2' | '/event/$date'
  fileRoutesByTo: FileRoutesByTo
  to: '/page2' | '/event/$date'
  id:
    | '__root__'
    | '/_pathlessLayout'
    | '/page2'
    | '/_pathlessLayout/event/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PathlessLayoutRouteRoute: typeof PathlessLayoutRouteRouteWithChildren
  Page2Route: typeof Page2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/page2': {
      id: '/page2'
      path: '/page2'
      fullPath: '/page2'
      preLoaderRoute: typeof Page2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/event/$date': {
      id: '/_pathlessLayout/event/$date'
      path: '/event/$date'
      fullPath: '/event/$date'
      preLoaderRoute: typeof PathlessLayoutEventDateRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
  }
}

interface PathlessLayoutRouteRouteChildren {
  PathlessLayoutEventDateRoute: typeof PathlessLayoutEventDateRoute
}

const PathlessLayoutRouteRouteChildren: PathlessLayoutRouteRouteChildren = {
  PathlessLayoutEventDateRoute: PathlessLayoutEventDateRoute,
}

const PathlessLayoutRouteRouteWithChildren =
  PathlessLayoutRouteRoute._addFileChildren(PathlessLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PathlessLayoutRouteRoute: PathlessLayoutRouteRouteWithChildren,
  Page2Route: Page2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
