/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Page2RouteImport } from './routes/page2'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventDateRouteImport } from './routes/event.$date'

const Page2Route = Page2RouteImport.update({
  id: '/page2',
  path: '/page2',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventDateRoute = EventDateRouteImport.update({
  id: '/event/$date',
  path: '/event/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/page2': typeof Page2Route
  '/event/$date': typeof EventDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/page2': typeof Page2Route
  '/event/$date': typeof EventDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/page2': typeof Page2Route
  '/event/$date': typeof EventDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/page2' | '/event/$date'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/page2' | '/event/$date'
  id: '__root__' | '/' | '/page2' | '/event/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Page2Route: typeof Page2Route
  EventDateRoute: typeof EventDateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/page2': {
      id: '/page2'
      path: '/page2'
      fullPath: '/page2'
      preLoaderRoute: typeof Page2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$date': {
      id: '/event/$date'
      path: '/event/$date'
      fullPath: '/event/$date'
      preLoaderRoute: typeof EventDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Page2Route: Page2Route,
  EventDateRoute: EventDateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
